

services:
    oracle-db:
      image: "harbor.hyvatech.com/ai/oracle:23.8.0.0-lite"
      restart: "unless-stopped"
      ports:
        - 1521:1521
        - 5500:5500
      volumes:
        - oradata:/opt/oracle/oradata
        - ./setup-scripts:/opt/oracle/scripts/setup
        - ./dump:/opt/oracle/dump
      environment:

        - ORACLE_PDB=nestjs
        - ORACLE_PWD=nestjs
        - ORACLE_CHARACTERSET=AL32UTF8 #UTF8
        
        - ENABLE_ARCHIVELOG=true 
        - ENABLE_FORCE_LOGGING=true
          
        ## schema of the dump you want to import
        # - "SOURCE_SCHEMA=change-or-delete-me"


volumes:
  oradata:
    external: false
